### PR TITLE
Add WP-CLI command

### PR DESCRIPTION
**Pull request by mboynes**
I'm still testing this out, but wanted to put it in front of you sooner rather than later. First off, thanks for this plugin, it's extremely helpful.

I added a WP-CLI command for this plugin. It can list shared terms in a variety of formats and split all of them. Let me know if you're interested in this PR and I'll finish it up.

Thanks!

### CODE REVIEW

**Comment by jjeaton** [comment]
@mboynes this is great! Am definitely interested in merging it. Let me know if you need anything, otherwise looking forward to merging once you're finished.

**Comment by mboynes** [comment]
I was going to attempt to make another command to help fix issues, but it got way too complicated too quickly. This PR is all set now for your review and merge!

**Comment by mboynes** [comment]
@jjeaton after you merge this, I'm going to ask VIP to add it to their shared plugins repo.

**Comment by jjeaton** [comment]
Sounds good. I can review/merge this evening.

**Comment by jjeaton** [comment]
@mboynes thanks for the PR! :+1: 

There were just a few minor commenting changes, I merged and made those changes afterwards. All good. It might be nice to be able to run the dry run split on a site that's not on 4.2 yet, but that's not a huge deal.

Let me know what else you'd need from me to get this on VIP if they want it.

Also curious to know what you were working towards on the command to help fix the issues.

**Pull request merged**
